name: 'Get Conan'
description: 'Installs Conan'
author: 'TurtleBrowser'
inputs:
  version:
    description: "Wanted conan version"
    required: false
    default: ''
outputs:
  version:
    description: "The version of Conan which was installed"
    value: ${{ steps.output_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.6"
    - name: Install setup tools
      run: pip3 install --user wheel setuptools
      shell: bash
    - name: Install conan latest
      if: ${{ inputs.version == '' }}
      run: pip3 install --user conan --upgrade
      shell: bash
    - name: Install conan version ${{ inputs.version }}
      if: ${{ inputs.version != '' }}
      run: pip3 install --user conan==${{ inputs.version }} --upgrade
      shell: bash
    - name: Fix path on Linux
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Fill in output variable
      id: output_version
      shell: bash
      run: |
        conan --version
        echo "version=$(conan --version)" >> $GITHUB_OUTPUT
branding:
  icon: "archive"
  color: "green"
